import "@/app/globals.css";
import type { Metadata } from "next";

import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
